//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPLServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionDetail
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> BidAmount { get; set; }
        public Nullable<int> NextMaxBid { get; set; }
        public Nullable<int> RemainingAmount { get; set; }
    }
}
