//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPLServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamDetail
    {
        public int Id { get; set; }
        public string TeamName { get; set; }
        public int TeamAmount { get; set; }
        public int RemainingAmount { get; set; }
        public int MaxBidAmount { get; set; }
        public int PlayerCount { get; set; }
        public string TeamOwner1 { get; set; }
        public string TeamOwner2 { get; set; }
        public string Mentor { get; set; }
        public string TeamLogo { get; set; }
    }
}
